name: Fire Danger Warning (täglich 07:00)

on:
  schedule:
    - cron: "0 5 * * *"   # 05:00 UTC = 07:00 MESZ
    - cron: "0 6 * * *"   # 06:00 UTC = 07:00 MEZ
  workflow_dispatch:

concurrency:
  group: fire-daily
  cancel-in-progress: false

jobs:
  daily:
    runs-on: ubuntu-latest
    env:
      STATE_CACHE_PREFIX: fire-state-v1-
      STATE_CACHE_KEY: fire-state-v1-${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Ensure state dir exists
        run: mkdir -p .state

      - name: Restore state cache (latest by prefix)
        uses: actions/cache/restore@v4
        with:
          path: .state
          key: ${{ env.STATE_CACHE_KEY }}
          restore-keys: |
            ${{ env.STATE_CACHE_PREFIX }}

      - name: Install deps
        run: python -m pip install --upgrade requests

      - name: Run daily forecast check
        env:
          DIVERA_ACCESSKEY_INFO: ${{ secrets.DIVERA_ACCESSKEY_INFO }}
          FIRE_RIC: "#170001"
          FIRE_MODE: "daily"
          STATE_FILE: ".state/fire_state.json"
          LAT: "51.15608"
          LON: "6.66705"
          TMAX_C: "10"
          RH_MIN: "80"
          WIND_MEAN_KMH: "15"
          WIND_GUST_KMH: "20"
          MODEL_PREF: "icon_d2,icon_eu,gfs"
        run: python fire_danger_watch.py

      - name: Save updated state cache (unique key)
        uses: actions/cache/save@v4
        with:
          path: .state
          key: ${{ env.STATE_CACHE_KEY }}
