name: Fire Danger Warning (akut)

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

concurrency:
  group: fire-acute
  cancel-in-progress: false

jobs:
  acute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Ensure state dir exists
        run: mkdir -p .state

      - name: Restore state cache
        uses: actions/cache/restore@v4
        with:
          path: .state
          key: fire-state-v1

      - name: Install deps
        run: python -m pip install --upgrade requests

      - name: Run acute check (hysterese)
        env:
          DIVERA_ACCESSKEY_INFO: ${{ secrets.DIVERA_ACCESSKEY_INFO }}
          FIRE_RIC: "#170001"
          FIRE_MODE: "acute"
          STATE_FILE: ".state/fire_state.json"
          LAT: "51.15608"
          LON: "6.66705"
          TMAX_C: "10"
          RH_MIN: "80"
          WIND_MEAN_KMH: "15"
          WIND_GUST_KMH: "20"
          MODEL_PREF: "icon_d2,icon_eu,gfs"
        run: |
          python fire_danger_watch.py

      - name: Save state cache
        uses: actions/cache/save@v4
        with:
          path: .state
          key: fire-state-v1
